#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x91C559DBE4C9123B (aperez@igalia.com)
#
Name     : WPEBackend-fdo
Version  : 1.14.1
Release  : 1
URL      : https://github.com/Igalia/WPEBackend-fdo/releases/download/1.14.1/wpebackend-fdo-1.14.1.tar.xz
Source0  : https://github.com/Igalia/WPEBackend-fdo/releases/download/1.14.1/wpebackend-fdo-1.14.1.tar.xz
Source1  : https://github.com/Igalia/WPEBackend-fdo/releases/download/1.14.1/wpebackend-fdo-1.14.1.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: WPEBackend-fdo-lib = %{version}-%{release}
Requires: WPEBackend-fdo-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : glib-dev
BuildRequires : libepoxy-dev
BuildRequires : pkgconfig(epoxy)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(wayland-scanner)
BuildRequires : pkgconfig(wpe-1.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package dev
Summary: dev components for the WPEBackend-fdo package.
Group: Development
Requires: WPEBackend-fdo-lib = %{version}-%{release}
Provides: WPEBackend-fdo-devel = %{version}-%{release}
Requires: WPEBackend-fdo = %{version}-%{release}

%description dev
dev components for the WPEBackend-fdo package.


%package lib
Summary: lib components for the WPEBackend-fdo package.
Group: Libraries
Requires: WPEBackend-fdo-license = %{version}-%{release}

%description lib
lib components for the WPEBackend-fdo package.


%package license
Summary: license components for the WPEBackend-fdo package.
Group: Default

%description license
license components for the WPEBackend-fdo package.


%prep
%setup -q -n wpebackend-fdo-1.14.1
cd %{_builddir}/wpebackend-fdo-1.14.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1679077023
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/WPEBackend-fdo
cp %{_builddir}/wpebackend-fdo-%{version}/COPYING %{buildroot}/usr/share/package-licenses/WPEBackend-fdo/2a3f54b72a02e0baf76735d4fa5df07b281668c7 || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/wpe-fdo-1.0/wpe/exported-buffer-shm.h
/usr/include/wpe-fdo-1.0/wpe/exported-image-egl.h
/usr/include/wpe-fdo-1.0/wpe/extensions/audio.h
/usr/include/wpe-fdo-1.0/wpe/extensions/video-plane-display-dmabuf.h
/usr/include/wpe-fdo-1.0/wpe/fdo-egl.h
/usr/include/wpe-fdo-1.0/wpe/fdo.h
/usr/include/wpe-fdo-1.0/wpe/initialize-egl.h
/usr/include/wpe-fdo-1.0/wpe/unstable/dmabuf-pool-entry.h
/usr/include/wpe-fdo-1.0/wpe/unstable/fdo-dmabuf.h
/usr/include/wpe-fdo-1.0/wpe/unstable/fdo-eglstream.h
/usr/include/wpe-fdo-1.0/wpe/unstable/fdo-shm.h
/usr/include/wpe-fdo-1.0/wpe/unstable/initialize-dmabuf.h
/usr/include/wpe-fdo-1.0/wpe/unstable/initialize-eglstream.h
/usr/include/wpe-fdo-1.0/wpe/unstable/initialize-shm.h
/usr/include/wpe-fdo-1.0/wpe/unstable/view-backend-dmabuf-pool-fdo.h
/usr/include/wpe-fdo-1.0/wpe/unstable/view-backend-exportable-eglstream.h
/usr/include/wpe-fdo-1.0/wpe/version.h
/usr/include/wpe-fdo-1.0/wpe/view-backend-exportable-egl.h
/usr/include/wpe-fdo-1.0/wpe/view-backend-exportable.h
/usr/include/wpe-fdo-1.0/wpe/wpebackend-fdo-version.h
/usr/lib64/libWPEBackend-fdo-1.0.so
/usr/lib64/pkgconfig/wpebackend-fdo-1.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libWPEBackend-fdo-1.0.so.1
/usr/lib64/libWPEBackend-fdo-1.0.so.1.9.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/WPEBackend-fdo/2a3f54b72a02e0baf76735d4fa5df07b281668c7
